US-006 Modificación de libro
GustavoCarvallo/bibliotecame-front pull request #12
Opened 2020-09-10 01:46 UTC by FacundoBocalandro

2020-09-10 05:11 UTC, GustavoCarvallo commented on src/Book/Book.tsx
> +    const [status, setStatus] = React.useState(EDIT);
Entiendo que por default la pantalla es edit porque si no, actualmente no podriamos llegar al edit (ya que no tenemos listar libros). Por ahora esta perfecto, cuando se agregue el listado de libros la pagina por default deberia ser SEARCH.

2020-09-10 05:17 UTC, GustavoCarvallo commented on src/Book/CreateOrEditBook.css
> +.input {
Agregar un pequeño padding-left (10px aprox) para que el texto se separe un poco mas de los bordes.

2020-09-10 05:20 UTC, GustavoCarvallo commented on src/Book/CreateOrEditBook.css
> +.save-button {
En todos los botones se deberia cambiar el cursor por 'pointer' cuando se esta haciendo hover sobre ellos.

2020-09-10 05:24 UTC, GustavoCarvallo commented on src/Book/CreateOrEditBook.css
> +.error-box {
Centrar el texto del error. Se recomienda usar [flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/). En este caso bastaria con solo agregar:
`
display: flex;
align-items: center;
justify-content: center;
`

2020-09-10 05:31 UTC, GustavoCarvallo commented on src/Book/CreateOrEditBook.tsx
> +                </button>
Separar un poco mas los botones, veo que estas tratando de imitar la funcionalidad de otras librerias como bootstrap o material. Si te sirve tratar de replicar eso que te dan las librerias me parece genial. De todas formas te recomiendo nuevamente que le pegues una mirada a flexbox.

2020-09-10 05:35 UTC, GustavoCarvallo commented on src/Book/CreateOrEditBook.tsx
> +                </button>
Con repecto al boton de guardar lo que se buscaba era que cuando alguno de los campos requeridos no estuviera completo el boton se deshabilitara (y ahi mostrara ese color gris en vez del azul). De esta forma no tendrias que preocuparte por los errores del campos requeridos solo por los de alguna validacion extra o por errores del back

2020-09-10 05:45 UTC, GustavoCarvallo requested changes
En lineas generales esta muy bien. Muy buen codigo!

Entiendo que esta faltando lo siguiente:
-  Añadir nuevo ejemplar (para lo cual necesitas el modal).

Note lo siguiente:
- La request de alta de libro no esta funcionando (usaste alguna branch en particular del back?)
- La request de modificacion de libro no esta funcionando (usaste alguna branch en particular del back?). Se podria harcodear una id de libro y unos datos para probar la integracion.

Por ultimo revisa un poco los comentarios que te deje.

2020-09-10 06:02 UTC, GustavoCarvallo commented on src/Book/CreateOrEditBook.tsx
> +                </button>
Por ahora descartar este comentario, porque vi que esta implementado asi en otros lugares tambien. Discutiremos con los pms si lo cambiamos o lo dejamos como esta.

2020-09-10 20:51 UTC, FacundoBocalandro commented on src/Book/Book.tsx
> +    const [status, setStatus] = React.useState(EDIT);
Así es, lo puse para que no tengas que hacer alguna maniobra rara para llegar al edit.

2020-09-10 22:40 UTC, FacundoBocalandro commented on src/Book/CreateOrEditBook.tsx
> +                </button>
Dale, espero a eso.

2020-09-12 19:33 UTC, GustavoCarvallo requested changes
Por favor resolver los 2 comentarios nuevos

2020-09-12 19:33 UTC, GustavoCarvallo commented on src/Book/CreateOrEditBook.tsx
> +        setErrors({...errors, serverError: undefined})
Si seteas 'errors' de nuevo en el state, si hubo un error de validacion (por ejemplo el autor no habia sido puesto) el error de validacion va a seguir estado aun cuando agregues el autor y la request vaya bien. 

Aca deberias setear todos los errors como todos false, te podrias crear un objeto 'initialErrors; y usarlo aca como tambien en el initial state del useState.

2020-09-12 19:33 UTC, GustavoCarvallo commented on src/Book/CreateOrEditBook.css
> +.tag {
Agregar un margin-left de 10px para que no queden pegados los tags

2020-09-12 19:51 UTC, GustavoCarvallo commented on src/Book/CreateOrEditBook.tsx
> +        setErrors({...errors, serverError: undefined})
done

2020-09-12 19:51 UTC, GustavoCarvallo commented on src/Book/CreateOrEditBook.css
> +.tag {
done

2020-09-12 19:57 UTC, GustavoCarvallo approved these changes
LGTM

2020-09-12 19:57 UTC, merged