US 045 dashboard for admin
GustavoCarvallo/bibliotecame-front pull request #74
Opened 2020-11-05 15:43 UTC by rocioferreiro

## Description

> Dashboard has relevant information for the admin user. AmountComponent shows numeric information, such as delayed loans, and total amount of books. ChartComponent is used to display information in the form of a chart, right now only takes line charts or doughnuts. The rest of the information is displayed in tables.
## ClubHouse Link

> https://app.clubhouse.io/bibliotecame/story/303/dashboard-admin
## Checklist
- [X] I've manually tested the feature and it works as expected
- [X] I've successfully integrated the feature with the API
- [X] This pull request has 'sprint_x' as the base branch
- [X] This pull request has a descriptive title and description
- [X] I have merged the current sprint into my branch before pushing
- [X] I've added the QA Leader as a reviewer

2020-11-07 15:06 UTC, FacundoBocalandro requested changes
Revisar layout del contenedor

![Screenshot from 2020-11-07 12-04-19](https://user-images.githubusercontent.com/43206864/98444635-870e4a80-20f1-11eb-80f9-fb7faccf46fe.png)

2020-11-07 15:14 UTC, FacundoBocalandro commented on src/Dashboard/Dashboard.tsx
> +    const reduce = (key : string) => {
Modificar nombre, por ejemplo abbreviateDate(...)

2020-11-07 15:20 UTC, FacundoBocalandro commented on src/Dashboard/Dashboard.tsx
> +type MapEntry = {
Modificar nombre para que sea más específico, por ejemplo DateTuple

2020-11-07 15:23 UTC, FacundoBocalandro commented on src/Dashboard/ChartComponent/ChartComponent.tsx
> +    options?: any,
Intercalar con el de abajo

2020-11-07 15:26 UTC, FacundoBocalandro commented on src/Dashboard/Table/BestReviewsTable.tsx
> +    data: any[],
Cambiar por Book[]

2020-11-07 15:27 UTC, FacundoBocalandro commented on src/Dashboard/Table/MostLoanedTable.tsx
> +    data: any[],
Cambiar por Book[]

2020-11-07 15:32 UTC, FacundoBocalandro commented on src/Dashboard/Dashboard.css
> +    max-height: 700px;
Cambiar a viewport

2020-11-07 15:33 UTC, FacundoBocalandro commented on src/Dashboard/Table/tables.css
> +    height: 5rem;
Cambiar a viewport

2020-11-07 15:34 UTC, FacundoBocalandro requested changes
Revisar

2020-11-08 15:13 UTC, rocioferreiro commented
@FacundoBocalandro ahi debería estar

2020-11-08 15:19 UTC, FacundoBocalandro approved these changes
LGTM

2020-11-08 15:40 UTC, LucasManza requested changes
Ver si es posible habilitar la animación del grafico de lineas
![image](https://user-images.githubusercontent.com/22375667/98469635-8c39cb00-21bf-11eb-99d4-5f2210f1215a.png)
Ref: https://www.chartjs.org/samples/latest/scales/logarithmic/line.html

2020-11-08 15:42 UTC, LucasManza commented
Revisar Layout  --> Resolución 1920x1080
![image](https://user-images.githubusercontent.com/22375667/98469681-d7ec7480-21bf-11eb-9a8d-3fedaf9762d9.png)

2020-11-08 20:47 UTC, rocioferreiro commented
@LucasManza listo los cambios

2020-11-08 21:16 UTC, LucasManza approved these changes

2020-11-08 21:16 UTC, merged