Feat Change App Styling
GustavoCarvallo/bibliotecame-front pull request #75
Opened 2020-11-07 16:02 UTC by FacundoBocalandro

## Description

User should see the new theme colors on the sidebar, topbar, buttons and modal.
## ClubHouse Link

https://app.clubhouse.io/bibliotecame/story/329/cambiar-styling-de-la-app
## Checklist
- [X] I've manually tested the feature and it works as expected
- [] I've successfully integrated the feature with the API
- [X] This pull request has 'sprint_x' as the base branch
- [X] This pull request has a descriptive title and description
- [X] I have merged the current sprint into my branch before pushing
- [X] I've added the QA Leader as a reviewer

2020-11-07 18:56 UTC, rocioferreiro requested changes
Cambiar color del boton de eliminar. (Nuevo verde)

![Screen Shot 2020-11-07 at 15 43 20](https://user-images.githubusercontent.com/43883272/98449319-49b9b500-2111-11eb-8bc6-33413998ae2c.png)

2020-11-07 18:56 UTC, rocioferreiro commented
Puede quedar mejor sin esta linea
![Screen Shot 2020-11-07 at 15 44 57](https://user-images.githubusercontent.com/43883272/98449374-d3698280-2111-11eb-805d-230309de94df.png)

2020-11-08 04:22 UTC, LucasManza requested changes
El boton parece que tiene una font color distinta al turquesa de la nueva paleta de colores.
![image](https://user-images.githubusercontent.com/22375667/98456643-f79f8080-215e-11eb-9bc8-be5e9e45f49a.png)

Cambiar los iconos a color rojo-coral, de la nueva paleta de colores.
![image](https://user-images.githubusercontent.com/22375667/98456682-582ebd80-215f-11eb-8f59-ec1e451fa5bb.png)

Verificar con @GustavoCarvallo si los iconos del a tabla a ver deberian estar en color
![image](https://user-images.githubusercontent.com/22375667/98456717-e6a33f00-215f-11eb-80f7-40fa809258c8.png)

Definir con @GustavoCarvallo la minima paletta de colores, en mi opinion, el turquesa, azul-oscuro, celeste (u otro), y el rojo-coloral, deberian ser los basicos (4 colores). Despues tenemos muchos colores mezclados, ejemplos:
![image](https://user-images.githubusercontent.com/22375667/98456846-63ceb400-2160-11eb-9e47-c250467f6ebc.png)
![image](https://user-images.githubusercontent.com/22375667/98456863-70eba300-2160-11eb-8af8-b001d67d2fd7.png)

2020-11-08 14:23 UTC, FacundoBocalandro commented
Listo @LucasManza. Las tablas ahora usan los colores que se usan en el resto de la aplicación. Agregué un único color (amarillo) que se usa para uno de los chips de la tabla (ya que son 5 y todos deben tener colores distintos). Igualmente, es un chip poco frecuente, el de pendiente de aprobación de una extensión para el administrador.
En cuanto al color del icono de visualizar, se decidió junto a @GustavoCarvallo que quede en negro.

2020-11-08 20:12 UTC, LucasManza approved these changes

2020-11-08 20:13 UTC, merged