Added new password update flow
GustavoCarvallo/bibliotecame-front pull request #76
Opened 2020-11-08 12:55 UTC by kuhamaven

## Description

El usuario ahora es capaz de modificar su perfil por separado de su contraseña, y cuenta con un botón nuevo para acceder al modal que le permite modificar solo su contraseña.

## ClubHouse Link

> https://app.clubhouse.io/bibliotecame/story/307/modificar-contrase%C3%B1a-nuevo-flujo
## Checklist

- [x] I've manually tested the feature and it works as expected
- [x] I've successfully integrated the feature with the API
- [x] This pull request has 'sprint_x' as the base branch
- [x] This pull request has a descriptive title and description
- [x] I have merged the current sprint into my branch before pushing
- [x] I've added the QA Leader as a reviewer

2020-11-08 14:05 UTC, LucasManza commented
Agregar dev reviewer

2020-11-08 14:36 UTC, LucasManza requested changes
- Definir dos rows la primera que contenga el boton de cambiar contraseña, y la segunda que tenga lo botones de eliminar y Guardar
- Los tres botones tengan el mismo border radius
- Eliminar y Guardar que tengan el mismo tamaño
- Reducir el tamaño del boton de cambiar contraseña para que sea mas estetico. Parece que tiene un estilo de disabled (todo gris) cambiarlo.

![image](https://user-images.githubusercontent.com/22375667/98467896-af13b180-21b6-11eb-8223-8a8b376b4d51.png)

**_Al cancelar el modal, no se borra el estado de los inputs. Deberian borrarse_**
![image](https://user-images.githubusercontent.com/22375667/98468314-b50a9200-21b8-11eb-86e3-fb5d507f8e81.png)

2020-11-08 15:03 UTC, LucasManza commented
Aumentar los paddings laterales
![image](https://user-images.githubusercontent.com/22375667/98468659-3d3d6700-21ba-11eb-9699-8450da6008bd.png)

2020-11-08 17:46 UTC, rocioferreiro requested changes

2020-11-08 17:46 UTC, rocioferreiro commented on src/Profile/EditPassword/EditPassword.css
> +    padding: 22px 60px;
usar viewports, no px. (Se repite en varios lugares)

2020-11-08 17:46 UTC, rocioferreiro commented on src/Profile/EditPassword/EditPassword.css
> +    border-color: #47a3fb;
Evitar usar colores sin usar las variables.

2020-11-08 17:46 UTC, rocioferreiro commented on src/Profile/EditPassword/EditPassword.tsx
> +        toast.error(message, toastifyConfiguration);
toastifyConfiguration alinea el toast al "centro" teniendo en cuenta el sidebar. 
Para que quede alineado con el modal no hay que ponerlo.

![Screen Shot 2020-11-08 at 14 21 57](https://user-images.githubusercontent.com/43883272/98472279-d9726880-21d0-11eb-9030-58638902ba25.png)

2020-11-08 17:46 UTC, rocioferreiro commented on src/Profile/EditPassword/EditPassword.tsx
> +    const [errors, setErrors] = React.useState<Errors>(initialErrors);
Tiene sentido esta variable si no se usa en ningún lado?

2020-11-08 17:46 UTC, rocioferreiro commented on src/Styles/main.css
> +    --cool-grey: #ffffff;
Por qué cambiaste la variable?

2020-11-08 20:17 UTC, LucasManza commented on src/Profile/EditPassword/EditPassword.css
> +    padding: 22px 60px;
Usar valores viewports si trabajan sobre layout. Para inputs o cosas fijas usar px.

2020-11-10 02:10 UTC, rocioferreiro approved these changes
LGTM

2020-11-10 13:17 UTC, LucasManza requested changes
Revisar tira toast con error de mensaje _No message available_
![image](https://user-images.githubusercontent.com/22375667/98678815-e5c80400-233d-11eb-8d27-4b8fa11e099f.png)

2020-11-10 13:28 UTC, kuhamaven commented
@LucasManza ahi estoy revisandolo, en que branch del back estabas?

2020-11-10 13:31 UTC, LucasManza commented
> @LucasManza ahi estoy revisandolo, en que branch del back estabas?

![image](https://user-images.githubusercontent.com/22375667/98680242-e3ff4000-233f-11eb-8edb-10b0937482ed.png)

2020-11-10 13:34 UTC, kuhamaven commented
> > @LucasManza ahi estoy revisandolo, en que branch del back estabas?
> 
> ![image](https://user-images.githubusercontent.com/22375667/98680242-e3ff4000-233f-11eb-8edb-10b0937482ed.png)

Ahi lo fixié, fue por el cambio de la url que meti en el back, me habia olvidado el cambio en el front

2020-11-10 14:01 UTC, LucasManza commented
> > > @LucasManza ahi estoy revisandolo, en que branch del back estabas?
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/22375667/98680242-e3ff4000-233f-11eb-8edb-10b0937482ed.png)
> 
> Ahi lo fixié, fue por el cambio de la url que meti en el back, me habia olvidado el cambio en el front

Ok aprobado, @kuhamaven y @rocioferreiro recuerden chequear que ande el flujo de la funcionalidad antes mandar pr o solicitar review. Por favor esten atentos a esto.

2020-11-10 14:02 UTC, LucasManza approved these changes

2020-11-10 14:06 UTC, merged