Code clean up
GustavoCarvallo/bibliotecame-front pull request #88
Opened 2020-11-14 04:44 UTC by rocioferreiro

## Description

> General resolution of warnings, removed unused code and variables.
## ClubHouse Link

> https://app.clubhouse.io/bibliotecame/story/352/code-cleanup
## Checklist
- [X] I've manually tested the feature and it works as expected
- [X] I've successfully integrated the feature with the API
- [X] This pull request has 'sprint_x' as the base branch
- [X] This pull request has a descriptive title and description
- [X] I have merged the current sprint into my branch before pushing
- [X] I've added the QA Leader as a reviewer

2020-11-14 13:17 UTC, FacundoBocalandro requested changes
Chequear la consola de chrome, donde aparecen los warnings de React. La mayoría son con respecto a las keys. Simplemente es agregar la prop key en los componentes que se renderizan con la función map.

![image](https://user-images.githubusercontent.com/43206864/99147781-6a7a9100-2662-11eb-9652-427b8ad6b8d6.png)

2020-11-14 21:48 UTC, FacundoBocalandro commented on src/Dashboard/Dashboard.tsx
> -    }, [])
No saques los [], se manda infinitamente la request.

2020-11-14 21:53 UTC, FacundoBocalandro commented on src/Login/VerifyToken.tsx
> +    }, )
Dejar los [].

2020-11-14 21:58 UTC, FacundoBocalandro requested changes
Ver comentarios

2020-11-14 22:38 UTC, rocioferreiro commented on src/Dashboard/Dashboard.tsx
> -    }, [])
arreglado

2020-11-14 22:38 UTC, rocioferreiro commented on src/Login/VerifyToken.tsx
> +    }, )
arreglado

2020-11-15 01:00 UTC, FacundoBocalandro approved these changes
LGTM. Great job!

2020-11-15 17:08 UTC, LucasManza approved these changes

2020-11-15 17:08 UTC, merged